"""OpenSCAD code generator for EoStudio 3D components."""

from __future__ import annotations

from typing import Any, Dict, List


class OpenSCADGenerator:
    """Generates OpenSCAD (.scad) source code from eostudio 3D component trees.

    Component type mapping:
    - ``cube``       -> ``cube(size)``
    - ``sphere``     -> ``sphere(r)``
    - ``cylinder``   -> ``cylinder(h, r)``
    - ``difference`` -> ``difference()``
    - ``union``      -> ``union()``
    - ``intersection`` -> ``intersection()``
    """

    def generate(self, components: List[Dict[str, Any]]) -> str:
        """Generate OpenSCAD source code.

        Args:
            components: List of 3D component dicts.

        Returns:
            OpenSCAD source code string.
        """
        lines: List[str] = []
        lines.append("// Generated by EoStudio")
        lines.append("$fn = 64;\n")

        if not components:
            lines.append("// Default scene")
            lines.append("cube(1);")
            return "\n".join(lines) + "\n"

        for comp in components:
            lines.append(self._render_component(comp, indent=0))

        return "\n".join(lines) + "\n"

    def _render_component(self, comp: Dict[str, Any], indent: int) -> str:
        pad = "  " * indent
        position = comp.get("position", None)
        color = comp.get("color", None)

        inner = self._render_primitive(comp, indent)

        if color:
            inner = f'{pad}color("{color}")\n{inner}'

        if position and any(v != 0 for v in position):
            pos_str = f"[{position[0]}, {position[1]}, {position[2]}]"
            inner = f"{pad}translate({pos_str})\n{inner}"

        return inner

    def _render_primitive(self, comp: Dict[str, Any], indent: int) -> str:
        pad = "  " * indent
        ctype = comp.get("type", "cube")
        children = comp.get("children", [])

        if ctype == "cube":
            size = comp.get("size", 1)
            return f"{pad}cube({size});\n"
        elif ctype == "sphere":
            radius = comp.get("radius", 1)
            return f"{pad}sphere(r={radius});\n"
        elif ctype == "cylinder":
            radius = comp.get("radius", 1)
            height = comp.get("height", 1)
            return f"{pad}cylinder(h={height}, r={radius});\n"
        elif ctype in ("difference", "union", "intersection"):
            child_lines = []
            for child in children:
                child_lines.append(self._render_component(child, indent + 1))
            child_body = "".join(child_lines)
            return f"{pad}{ctype}() {{\n{child_body}{pad}}}\n"
        else:
            size = comp.get("size", 1)
            return f"{pad}cube({size});\n"
