apiVersion: v2
name: eos-eosim
description: Simulation Server — EoS Enterprise Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: EmbeddedOS
    url: https://github.com/embeddedos-org
keywords:
  - eos
  - eosim
  - enterprise
