apiVersion: v2
name: eos-echat
description: Messaging Server — EoS Enterprise Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: EmbeddedOS
    url: https://github.com/embeddedos-org
keywords:
  - eos
  - echat
  - enterprise
