# SPDX-License-Identifier: MIT
# Copyright (c) 2026 EoS Project
"""Product template definitions for EoSim simulation UI."""
from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass
class ProductTemplate:
    name: str = ""
    display_name: str = ""
    icon: str = ""
    arch: str = "arm"
    ram_mb: int = 128
    peripherals: List[str] = field(default_factory=list)
    domain: str = ""
    modeling: str = "deterministic"
    description: str = ""
    default_platform: str = ""
    simulator_class: str = ""


PRODUCT_CATALOG: Dict[str, ProductTemplate] = {
    "iot_sensor": ProductTemplate(
        name="iot_sensor",
        display_name="IoT Sensor",
        icon="\U0001F4E1",
        arch="arm",
        ram_mb=64,
        peripherals=["uart", "gpio", "i2c", "temp", "adc", "ble", "lora"],
        domain="iot",
        modeling="deterministic",
        description="Low-power MCU for IoT sensor nodes — temperature, humidity, motion",
        default_platform="nrf52",
        simulator_class="IoTSimulator",
    ),
    "smart_home_hub": ProductTemplate(
        name="smart_home_hub",
        display_name="Smart Home Hub",
        icon="\U0001F3E0",
        arch="arm64",
        ram_mb=256,
        peripherals=["uart", "gpio", "spi", "i2c", "wifi", "zigbee", "ble"],
        domain="consumer",
        modeling="deterministic",
        description="ARM SoC hub for smart home device coordination and automation",
        default_platform="raspi4",
        simulator_class="IoTSimulator",
    ),
    "automotive_ecu": ProductTemplate(
        name="automotive_ecu",
        display_name="Automotive ECU",
        icon="\U0001F697",
        arch="arm",
        ram_mb=128,
        peripherals=["uart", "gpio", "timer", "can", "lin", "imu", "watchdog"],
        domain="automotive",
        modeling="deterministic",
        description="Safety-rated MCU for engine control, ADAS, body electronics",
        default_platform="s32k344",
        simulator_class="VehicleSimulator",
    ),
    "ev_powertrain": ProductTemplate(
        name="ev_powertrain",
        display_name="EV Powertrain",
        icon="\u26A1",
        arch="arm",
        ram_mb=256,
        peripherals=["can", "motor", "bms", "throttle", "brake", "imu", "gps"],
        domain="automotive",
        modeling="deterministic",
        description="EV powertrain controller — motor, BMS, regenerative braking",
        default_platform="s32k344",
        simulator_class="VehicleSimulator",
    ),
    "adas_controller": ProductTemplate(
        name="adas_controller",
        display_name="ADAS Controller",
        icon="\U0001F441",
        arch="arm64",
        ram_mb=512,
        peripherals=["can", "imu", "gps", "proximity", "ethernet"],
        domain="automotive",
        modeling="deterministic",
        description="ADAS sensor fusion controller — radar, camera, lidar processing",
        default_platform="jetson-orin",
        simulator_class="VehicleSimulator",
    ),
    "medical_monitor": ProductTemplate(
        name="medical_monitor",
        display_name="Medical Monitor",
        icon="\U0001FA7A",
        arch="arm",
        ram_mb=128,
        peripherals=["uart", "gpio", "ecg", "spo2", "temp", "display", "pump", "watchdog"],
        domain="medical",
        modeling="deterministic",
        description="MCU for patient vital signs monitoring and alarm systems",
        default_platform="stm32h7",
        simulator_class="MedicalSimulator",
    ),
    "drone_controller": ProductTemplate(
        name="drone_controller",
        display_name="Drone Controller",
        icon="\U0001F681",
        arch="arm",
        ram_mb=256,
        peripherals=["uart", "gpio", "esc", "imu", "gps", "barometer", "mag", "bms"],
        domain="robotics",
        modeling="deterministic",
        description="ARM MCU flight controller for UAV stabilization and navigation",
        default_platform="stm32f4",
        simulator_class="DroneSimulator",
    ),
    "industrial_plc": ProductTemplate(
        name="industrial_plc",
        display_name="Industrial PLC",
        icon="\U0001F3ED",
        arch="arm",
        ram_mb=128,
        peripherals=["uart", "gpio", "timer", "modbus", "relay", "adc", "motor", "watchdog"],
        domain="industrial",
        modeling="deterministic",
        description="MCU-based programmable logic controller for factory automation",
        default_platform="psoc6",
        simulator_class="IndustrialSimulator",
    ),
    "wearable_device": ProductTemplate(
        name="wearable_device",
        display_name="Wearable Device",
        icon="\u231A",
        arch="arm",
        ram_mb=32,
        peripherals=["uart", "i2c", "imu", "spo2", "ble", "display", "haptic", "bms"],
        domain="consumer",
        modeling="deterministic",
        description="Low-power MCU for fitness trackers, smartwatches, health bands",
        default_platform="nrf5340",
        simulator_class="WearableSimulator",
    ),
    "robot_controller": ProductTemplate(
        name="robot_controller",
        display_name="Robot Controller",
        icon="\U0001F916",
        arch="arm64",
        ram_mb=512,
        peripherals=["uart", "gpio", "servo", "imu", "proximity", "motor"],
        domain="robotics",
        modeling="deterministic",
        description="ARM64 SoC for industrial robot motion planning and sensor fusion",
        default_platform="jetson-orin",
        simulator_class="RobotSimulator",
    ),
    "fixed_wing": ProductTemplate(
        name="fixed_wing",
        display_name="Fixed-Wing Aircraft",
        icon="\u2708",
        arch="arm",
        ram_mb=256,
        peripherals=["servo", "imu", "gps", "barometer", "arinc429", "throttle"],
        domain="aerospace",
        modeling="deterministic",
        description="Flight controller for fixed-wing aircraft — autopilot, instruments",
        default_platform="stm32h7",
        simulator_class="AircraftSimulator",
    ),
    "cubesat": ProductTemplate(
        name="cubesat",
        display_name="CubeSat",
        icon="\U0001F6F0",
        arch="arm",
        ram_mb=128,
        peripherals=["imu", "gps", "adc", "bms", "rf", "motor", "crypto", "watchdog"],
        domain="aerospace",
        modeling="deterministic",
        description="CubeSat flight computer — attitude control, power, comms",
        default_platform="stm32h7",
        simulator_class="SatelliteSimulator",
    ),
    "solar_inverter": ProductTemplate(
        name="solar_inverter",
        display_name="Solar Inverter",
        icon="\u2600",
        arch="arm",
        ram_mb=128,
        peripherals=["adc", "bms", "relay", "modbus", "ethernet", "temp", "rtc"],
        domain="energy",
        modeling="deterministic",
        description="Solar inverter / battery storage controller for smart grid",
        default_platform="psoc6",
        simulator_class="EnergySimulator",
    ),
    "base_station_5g": ProductTemplate(
        name="base_station_5g",
        display_name="5G Base Station",
        icon="\U0001F4F6",
        arch="arm64",
        ram_mb=1024,
        peripherals=["ethernet", "rf", "adc", "gpio", "timer"],
        domain="telecom",
        modeling="deterministic",
        description="5G/LTE base station radio unit controller",
        default_platform="jetson-orin",
        simulator_class="BaseSimulator",
    ),
    "tactical_radio": ProductTemplate(
        name="tactical_radio",
        display_name="Tactical Radio",
        icon="\U0001F4FB",
        arch="arm64",
        ram_mb=256,
        peripherals=["rf", "crypto", "gps", "ethernet", "watchdog"],
        domain="defense",
        modeling="deterministic",
        description="Software-defined tactical radio with encryption",
        default_platform="stm32h7",
        simulator_class="BaseSimulator",
    ),
    "smart_meter": ProductTemplate(
        name="smart_meter",
        display_name="Smart Meter",
        icon="\U0001F50C",
        arch="arm",
        ram_mb=64,
        peripherals=["modbus", "rf", "adc", "relay", "rtc", "temp"],
        domain="energy",
        modeling="deterministic",
        description="Smart electricity/gas/water meter with RF communication",
        default_platform="psoc6",
        simulator_class="EnergySimulator",
    ),
    "surgical_robot": ProductTemplate(
        name="surgical_robot",
        display_name="Surgical Robot",
        icon="\U0001FA7C",
        arch="arm64",
        ram_mb=512,
        peripherals=["servo", "imu", "proximity", "watchdog"],
        domain="medical",
        modeling="deterministic",
        description="Precision surgical robot with force feedback and safety",
        default_platform="jetson-orin",
        simulator_class="RobotSimulator",
    ),
    "submarine": ProductTemplate(
        name="submarine",
        display_name="Autonomous Submarine",
        icon="\U0001F6A4",
        arch="arm64",
        ram_mb=512,
        peripherals=["imu", "gps", "proximity", "motor", "bms", "crypto", "barometer"],
        domain="defense",
        modeling="deterministic",
        description="Autonomous underwater vehicle — navigation, depth, comms",
        default_platform="stm32h7",
        simulator_class="BaseSimulator",
    ),
    "ag_drone": ProductTemplate(
        name="ag_drone",
        display_name="Agricultural Drone",
        icon="\U0001F33E",
        arch="arm",
        ram_mb=256,
        peripherals=["esc", "imu", "gps", "barometer", "bms", "relay"],
        domain="robotics",
        modeling="deterministic",
        description="Agricultural spraying drone with GPS waypoint navigation",
        default_platform="stm32f4",
        simulator_class="DroneSimulator",
    ),
    "electric_scooter": ProductTemplate(
        name="electric_scooter",
        display_name="Electric Scooter",
        icon="\U0001F6F4",
        arch="arm",
        ram_mb=64,
        peripherals=["motor", "bms", "imu", "ble", "display", "brake", "throttle"],
        domain="automotive",
        modeling="deterministic",
        description="Electric scooter/e-bike controller — motor, BMS, BLE unlock",
        default_platform="stm32f4",
        simulator_class="VehicleSimulator",
    ),
    "iptv_stb": ProductTemplate(
        name="iptv_stb",
        display_name="IPTV Set-top Box",
        icon="\U0001F4FA",
        arch="arm64",
        ram_mb=512,
        peripherals=["uart", "gpio", "hdmi", "wifi", "ethernet", "ir", "usb", "audio"],
        domain="consumer",
        modeling="deterministic",
        description="IPTV / set-top box — HDMI-CEC, streaming, EPG, DRM",
        default_platform="raspi4",
        simulator_class="MediaDeviceSimulator",
    ),
    "cast_device": ProductTemplate(
        name="cast_device",
        display_name="Cast Streaming Dongle",
        icon="\U0001F4E1",
        arch="arm",
        ram_mb=256,
        peripherals=["uart", "gpio", "hdmi", "wifi", "ble", "usb", "audio"],
        domain="consumer",
        modeling="deterministic",
        description="Chromecast-style streaming dongle — WiFi cast, HDMI output",
        default_platform="esp32s3",
        simulator_class="MediaDeviceSimulator",
    ),
    "smart_speaker": ProductTemplate(
        name="smart_speaker",
        display_name="Smart Speaker",
        icon="\U0001F50A",
        arch="arm",
        ram_mb=128,
        peripherals=["uart", "gpio", "wifi", "ble", "audio", "touch"],
        domain="consumer",
        modeling="deterministic",
        description="Smart speaker — wake word, voice commands, multi-room audio",
        default_platform="esp32",
        simulator_class="SmartSpeakerSimulator",
    ),
    "home_camera": ProductTemplate(
        name="home_camera",
        display_name="Home Security Camera",
        icon="\U0001F4F7",
        arch="arm",
        ram_mb=128,
        peripherals=["uart", "gpio", "wifi", "ble", "camera", "ir", "audio"],
        domain="consumer",
        modeling="deterministic",
        description="Home surveillance camera — motion detect, night vision, cloud upload",
        default_platform="esp32s3",
        simulator_class="HomeCameraSimulator",
    ),
    "tv_os": ProductTemplate(
        name="tv_os",
        display_name="TV Operating System",
        icon="\U0001F5A5",
        arch="arm64",
        ram_mb=1024,
        peripherals=["uart", "gpio", "hdmi", "wifi", "ble", "ethernet", "usb", "audio", "gpu", "ir", "touch"],
        domain="consumer",
        modeling="deterministic",
        description="Full TV operating system — apps, streaming, CEC, multi-codec",
        default_platform="raspi4",
        simulator_class="MediaDeviceSimulator",
    ),
    "vbox_test": ProductTemplate(
        name="vbox_test",
        display_name="VirtualBox Test OS",
        icon="\U0001F4BB",
        arch="x86_64",
        ram_mb=2048,
        peripherals=["uart", "gpio", "ethernet", "usb", "display", "audio", "pcie"],
        domain="consumer",
        modeling="deterministic",
        description="VirtualBox test OS — x86_64 POSIX compat, integration testing",
        default_platform="x86_64",
        simulator_class="BaseSimulator",
    ),
    "wind_tunnel": ProductTemplate(
        name="wind_tunnel",
        display_name="Wind Tunnel",
        icon="\U0001F32C",
        arch="x86_64",
        ram_mb=512,
        peripherals=["uart", "gpio", "adc", "wind_tunnel", "pitot", "force_balance"],
        domain="aerodynamics",
        modeling="cfd",
        description="Aerodynamics wind tunnel — lift/drag, airfoil analysis, CFD",
        default_platform="aerodynamics-sim",
        simulator_class="AerodynamicsSimulator",
    ),
    "patient_model": ProductTemplate(
        name="patient_model",
        display_name="Patient Physiology",
        icon="\U0001FAC0",
        arch="arm64",
        ram_mb=256,
        peripherals=["uart", "gpio", "ecg", "spo2", "temp", "pump", "heart_model", "bp_sensor"],
        domain="physiology",
        modeling="continuous",
        description="Patient physiology model — cardiovascular, respiratory, pharmacokinetics",
        default_platform="physiology-sim",
        simulator_class="PhysiologySimulator",
    ),
    "stock_market": ProductTemplate(
        name="stock_market",
        display_name="Financial Market",
        icon="\U0001F4C8",
        arch="x86_64",
        ram_mb=512,
        peripherals=["uart", "gpio", "ethernet", "market_feed", "order_book"],
        domain="finance",
        modeling="monte-carlo",
        description="Financial market simulator — GBM pricing, Monte Carlo risk, trading",
        default_platform="finance-sim",
        simulator_class="FinanceSimulator",
    ),
    "weather_station_sim": ProductTemplate(
        name="weather_station_sim",
        display_name="Weather System",
        icon="\U0001F326",
        arch="arm64",
        ram_mb=256,
        peripherals=["uart", "gpio", "temp", "barometer", "adc", "anemometer", "radar"],
        domain="weather",
        modeling="continuous",
        description="Weather & atmospheric simulation — pressure, precipitation, forecasting",
        default_platform="weather-sim",
        simulator_class="WeatherSimulator",
    ),
    "game_world": ProductTemplate(
        name="game_world",
        display_name="Game World",
        icon="\U0001F3AE",
        arch="x86_64",
        ram_mb=1024,
        peripherals=["uart", "gpio", "gpu", "physics_engine", "terrain", "entities"],
        domain="gaming",
        modeling="agent-based",
        description="Game world simulator — rigid body physics, entities, terrain, AI agents",
        default_platform="gaming-sim",
        simulator_class="GamingSimulator",
    ),
}


def get_template(name: str) -> Optional[ProductTemplate]:
    return PRODUCT_CATALOG.get(name)


def list_templates() -> List[str]:
    return sorted(PRODUCT_CATALOG.keys())
