set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(EOS_TOOLCHAIN_PREFIX "arm-none-eabi-" CACHE STRING "Cross-compiler prefix")

set(CMAKE_C_COMPILER   "${EOS_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${EOS_TOOLCHAIN_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${EOS_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_OBJCOPY      "${EOS_TOOLCHAIN_PREFIX}objcopy")
set(CMAKE_SIZE         "${EOS_TOOLCHAIN_PREFIX}size")

set(CMAKE_C_FLAGS_INIT   "-mcpu=cortex-a53 -mthumb -ffunction-sections -fdata-sections -fno-common")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,--gc-sections -specs=nosys.specs")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(EAPPS_PLATFORM_EOS ON CACHE BOOL "" FORCE)
